### ISSUE TITLE
Default write inline value (220) could be too large

### ISSUE THREAD

**Issue by Pusnow** [linux-rdma/perftest#139]
In perftest, default WRITE_INLINE is 220:

https://github.com/linux-rdma/perftest/blob/ed18d321da32d052f10d7e3e2442e6499de4078f/src/perftest_parameters.h#L137

However, 220 max_inline_data could be too large for some devices (e.g., Intel E810 only support max_inline_data less than 102).
Pertest has option (`-I`) to change the value, but users may not be aware of the option, and output is a bit unfriendly.

Output of `./ib_write_lat -s 64 -c RC -d irdma0 -n 1000 -i 1`:
```

************************************
* Waiting for client to connect... *
************************************
Unable to create QP.
Failed to create QP.
 Couldn't create IB resources
```

**Comment by sshaulnv** [comment]
The creation of QP is made by ibv_create_qp().
When the value of the max_inline_data is invalid, the function return EINVAL on the errno,
this kind of an error can be caused by: 	Invalid **pd**, **send_cq**, **recv_cq**, **srq** or invalid value provided in **max_send_wr**, **max_recv_wr**, **max_send_sge**, **max_recv_sge** or in **max_inline_data**.
Therefore, we can't determine what the exact problem that failed the QP creation, and this is why the output is as it is.
